// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230705074832_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargooReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargooReference = "C2023001999",
                            ServiceProviderName = "Service Provider 1"
                        },
                        new
                        {
                            Id = 2,
                            CargooReference = "C2023001888",
                            ServiceProviderName = "Service Provider 2"
                        },
                        new
                        {
                            Id = 3,
                            CargooReference = "C2023001777",
                            ServiceProviderName = "Service Provider 3"
                        });
                });

            modelBuilder.Entity("Domain.ShipmentContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentContainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "N0001",
                            OriginalType = "Open top container",
                            ShipmentId = 1,
                            Type = "42GP"
                        },
                        new
                        {
                            Id = 2,
                            Number = "N0002",
                            OriginalType = "Double door container",
                            ShipmentId = 1,
                            Type = "42GP"
                        },
                        new
                        {
                            Id = 3,
                            Number = "N0003",
                            OriginalType = "Double door container",
                            ShipmentId = 2,
                            Type = "48GP"
                        },
                        new
                        {
                            Id = 4,
                            Number = "N0004",
                            OriginalType = "Double door container",
                            ShipmentId = 2,
                            Type = "48GP"
                        },
                        new
                        {
                            Id = 5,
                            Number = "N0005",
                            OriginalType = "Double door container",
                            ShipmentId = 3,
                            Type = "48GP"
                        });
                });

            modelBuilder.Entity("Domain.ShipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommodityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Packages")
                        .HasColumnType("int");

                    b.Property<int?>("Pieces")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleCode = "ArticleCode 1",
                            ArticleDescription = "ArticleDescription 1",
                            CommodityCode = "CD",
                            PackageType = "PT1",
                            Packages = 5,
                            Pieces = 5,
                            ShipmentId = 1,
                            Volume = 5m
                        },
                        new
                        {
                            Id = 2,
                            ArticleCode = "ArticleCode 2",
                            ArticleDescription = "ArticleDescription 2",
                            CommodityCode = "CD",
                            PackageType = "PT1",
                            Packages = 5,
                            Pieces = 15,
                            ShipmentId = 2,
                            Volume = 15m
                        },
                        new
                        {
                            Id = 3,
                            ArticleCode = "ArticleCode 3",
                            ArticleDescription = "ArticleDescription 3",
                            CommodityCode = "CD",
                            PackageType = "PT1",
                            Packages = 5,
                            Pieces = 15,
                            ShipmentId = 2,
                            Volume = 15m
                        },
                        new
                        {
                            Id = 4,
                            ArticleCode = "ArticleCode 4",
                            ArticleDescription = "ArticleDescription 4",
                            CommodityCode = "CD",
                            PackageType = "PT1",
                            Packages = 15,
                            Pieces = 15,
                            ShipmentId = 2,
                            Volume = 15m
                        },
                        new
                        {
                            Id = 5,
                            ArticleCode = "ArticleCode 5",
                            ArticleDescription = "ArticleDescription 5",
                            CommodityCode = "CD",
                            PackageType = "PT4",
                            Packages = 15,
                            Pieces = 15,
                            ShipmentId = 3,
                            Volume = 15m
                        },
                        new
                        {
                            Id = 6,
                            ArticleCode = "ArticleCode 6",
                            ArticleDescription = "ArticleDescription 6",
                            CommodityCode = "CD",
                            PackageType = "PT8",
                            Packages = 8,
                            Pieces = 25,
                            ShipmentId = 3,
                            Volume = 20m
                        });
                });

            modelBuilder.Entity("Domain.ShipmentRemark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RemarkTemplateId")
                        .HasColumnType("bigint");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentRemarks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1459),
                            Remark = "Remark",
                            RemarkTemplateId = 1L,
                            ShipmentId = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1463),
                            Remark = "Remark 1",
                            RemarkTemplateId = 1L,
                            ShipmentId = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1464),
                            Remark = "Remark 2",
                            RemarkTemplateId = 1L,
                            ShipmentId = 1
                        },
                        new
                        {
                            Id = 4L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1465),
                            Remark = "Remark 7",
                            RemarkTemplateId = 2L,
                            ShipmentId = 2
                        },
                        new
                        {
                            Id = 5L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1467),
                            Remark = "Remark 8",
                            RemarkTemplateId = 2L,
                            ShipmentId = 2
                        },
                        new
                        {
                            Id = 6L,
                            CreatedById = 1L,
                            CreatedOn = new DateTime(2023, 7, 5, 7, 48, 32, 23, DateTimeKind.Utc).AddTicks(1468),
                            Remark = "Remark 8",
                            RemarkTemplateId = 2L,
                            ShipmentId = 3
                        });
                });

            modelBuilder.Entity("Domain.Stuffing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SealNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("TrackerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Stuffings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SealNumber = "SealNumber 1",
                            ShipmentId = 1,
                            TrackerNumber = "TrackerNumber 1"
                        },
                        new
                        {
                            Id = 2,
                            SealNumber = "SealNumber 2",
                            ShipmentId = 1,
                            TrackerNumber = "TrackerNumber 2"
                        },
                        new
                        {
                            Id = 3,
                            SealNumber = "SealNumber 3",
                            ShipmentId = 2,
                            TrackerNumber = "TrackerNumber 3"
                        },
                        new
                        {
                            Id = 4,
                            SealNumber = "SealNumber 4",
                            ShipmentId = 2,
                            TrackerNumber = "TrackerNumber 4"
                        },
                        new
                        {
                            Id = 5,
                            SealNumber = "SealNumber 5",
                            ShipmentId = 3,
                            TrackerNumber = "TrackerNumber 54"
                        });
                });

            modelBuilder.Entity("Domain.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierCode = "MAEU",
                            ShipmentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CarrierCode = "SLMU",
                            ShipmentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CarrierCode = "SLMU",
                            ShipmentId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CarrierCode = "MAEU",
                            ShipmentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CarrierCode = "SLMU",
                            ShipmentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CarrierCode = "SLMU",
                            ShipmentId = 3,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Domain.ShipmentContainer", b =>
                {
                    b.HasOne("Domain.Shipment", null)
                        .WithMany("Containers")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ShipmentItem", b =>
                {
                    b.HasOne("Domain.Shipment", null)
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ShipmentRemark", b =>
                {
                    b.HasOne("Domain.Shipment", null)
                        .WithMany("ShipmentRemarks")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Stuffing", b =>
                {
                    b.HasOne("Domain.Shipment", null)
                        .WithMany("Stuffings")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Transport", b =>
                {
                    b.HasOne("Domain.Shipment", null)
                        .WithMany("Transports")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Shipment", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Items");

                    b.Navigation("ShipmentRemarks");

                    b.Navigation("Stuffings");

                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
